name: HsiangNianian
permalink: :year/:month/:day/:title
baseurl: ''

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2018
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : admin@jyunko.cn
  github : HsiangNianian
  twitter : HsiangNianian

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
#    Diary: "/diary"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
